name: SFTP Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  deploy_job:
    runs-on: ubuntu-latest
    name: Build & Deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Deploy
        uses: wlixcc/SFTP-Deploy-Action@v1.0
        with:
          username: 'fretboard-hero_com'
          server: '${{ secrets.SERVER_DOMAIN }}'
          ssh_private_key: ${{ secrets.FRETHERO_KEY }}
          local_path: './dist/*'
          remote_path: '/var/www/vhosts/fretboard-hero.com/httpdocs'
          args: '-o ConnectTimeout=5'
