# This is a basic workflow that is manually triggered

name: SFTP Deploy

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

jobs:
  deploy_job:
    runs-on: ubuntu-latest
    name: build&deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm build

      - name: deploy file to server
        uses: wlixcc/SFTP-Deploy-Action@v1.0
        with:
          username: 'frethero'
          server: '${{ secrets.SERVER_DOMAIN }}'
          ssh_private_key: ${{ secrets.FRETHERO_KEY }}
          local_path: 'dist/*'
          remote_path: '/home/frethero/web/fretboard-hero.com/public_html'
          args: '-o ConnectTimeout=5'
